### ISSUE TITLE
Final Project feedback

### ISSUE THREAD

**Issue by kayroy247** [malawadd/blockchain-developer-bootcamp-final-project#1]
Hi @malawadd, I am a mentor helping with the grading.
Congratulations, your Final Project passed! We'll be approving it on the course itself in a week or two. Here is your feedback in the meanwhile:

### Frontend
- Good job with the NFT Gaming project. It has a good layout and style with game-themed texts. 
- Wallet Connected successfully. You can improve this by displaying the wallet address when connected. 
- Read and write transactions were executed successfully on the blockchain. 
- Your readme file is also well structured and detailed and a great project demo video.

### Smart Contract Design and Security
- Good use of openzepplins ERC721 through inheritance.
- Used specific compiler pragma and good use of access control on the contract
- Good Natspec comments 

### Testing
- Well-structured tests and covering most of the important functions of the contract.

Congratulations! once again.

**Comment by malawadd** [comment]
thank you so very much @kayroy247.
